### ISSUE TITLE
[next] Socket connection not working

### ISSUE THREAD

**Issue by dopecoder** [zino-app/graphql-flutter#134]
**Describe the bug**
Connecting to a socket connection fails. and it returns an error - 
Error : {type: connection_error, payload: parsing ClientMessage failed: Error in $: expected ClientMessage, encountered String} 
{type: error, id: e6d5801c-284b-4630-abac-37e9885c0b90, payload: start received before the connection is initialised}

**To Reproduce**
Connect to a socket connection and it displays this error message in the console,
I have tested my socket connection and it works perfectly with Apollo Graphql Client.

**Expected behavior**
Connect to a socket connection to be used in subscription.

**Screenshots**
![capture3](https://user-images.githubusercontent.com/3256139/48124832-50538e80-e2a3-11e8-84e4-c0673bc98aec.PNG)
Console output while connecting to socket

**Comment by HofmannZ** [comment]
Fixed by #147

**Comment by ArpanKIIT2017** [comment]
Not yet solved...I am also facing this issue. Although my websocket works perfectly with my react app.

**Comment by mainawycliffe** [comment]
what version of this app are you using?

**Comment by ArpanKIIT2017** [comment]
Version 1.0.0+4
I had to customize your code and make the following change to get it working:

`dynamic toJson() {
    final Map<String, dynamic> jsonMap = <String, dynamic>{};
    jsonMap['type'] = type;

    if (payload != null) {
      jsonMap['payload'] = json.encode(payload);
    }

    //return json.encode(jsonMap); Removed this line
    return jsonMap; // Instead returned the Map directly and all worked fine
  }`

**Comment by mainawycliffe** [comment]
Can you please check if this [example ](https://github.com/zino-app/graphql-flutter/tree/master/examples/starwars) is going to help, i know the documentation may not be up to date. It has a working subscription and is easy to get up and running on your device.

**Comment by truongsinh** [comment]
@ArpanKIIT2017 suggestion seems to be correct, I'm working on this.
